<Project>

	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<ItemGroup>
		<!-- API -->
		<PackageVersion Include="Azure.Monitor.OpenTelemetry.AspNetCore"
						Version="1.6.0" />
		<PackageVersion Include="Microsoft.AspNetCore.OpenApi"
						Version="10.0.10" />
		<PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.OpenApi"
						Version="2.7.5" />

		<PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing"
						Version="10.0.10" />
		<PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"
						Version="10.0.10" />

		<PackageVersion Include="Swashbuckle.AspNetCore"
						Version="10.2.3" />
		<PackageVersion Include="OpenTelemetry.Extensions.Hosting"
						Version="1.17.0" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore"
						Version="1.17.0" />
		<PackageVersion Include="OpenTelemetry.Instrumentation.Runtime"
						Version="1.17.0" />

		<!-- Infrastructure -->
		<PackageVersion Include="Microsoft.EntityFrameworkCore"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.Extensions.Configuration"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.Extensions.DependencyInjection"
						Version="10.0.10" />

		<PackageVersion Include="Microsoft.Extensions.Identity.Core"
						Version="10.0.10" />
		<PackageVersion Include="Microsoft.Extensions.Options"
						Version="10.0.10" />
		<PackageVersion Include="Resend"
						Version="0.7.0" />

		<PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3"
						Version="3.0.5" />

		<!-- Testing -->
		<PackageVersion Include="coverlet.collector"
						Version="6.0.4" />

		<PackageVersion Include="Microsoft.NET.Test.Sdk"
						Version="17.14.1" />

		<PackageVersion Include="xunit"
						Version="2.9.3" />

		<PackageVersion Include="xunit.runner.visualstudio"
						Version="3.1.4" />
	</ItemGroup>

</Project>
