<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	  <PackageReference Include="Microsoft.OpenApi" />
	  <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseIdentityService.Application\EnterpriseIdentityService.Application.csproj" />
    <ProjectReference Include="..\EnterpriseIdentityService.Infrastructure\EnterpriseIdentityService.Infrastructure.csproj" />
    <ProjectReference Include="..\EnterpriseIdentityService.Contracts\EnterpriseIdentityService.Contracts.csproj" />
  </ItemGroup>

</Project>
